// <auto-generated />
using LootStudios5eNames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LootStudios5eNames.Migrations
{
    [DbContext(typeof(LootStudios5eNamesContext))]
    partial class LootStudios5eNamesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LootStudios5eNames.Models.Miniature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LS_Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LS_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LS_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LS_Pack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LS_Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LS_Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LS_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_5e_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_5e_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_5e_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Miniature");
                });
#pragma warning restore 612, 618
        }
    }
}
